#!/usr/bin/env bash
set -E -e -o pipefail

# Add repo specific metadata here.

BASE_IMAGE_CONFIG_KEY_PREFIX="BASE_IMAGE"
PACKAGES_FILE_PACKAGE_NAME="postfix"

UPSTREAM_PACKAGE_NAME="Postfix"
UPSTREAM_VERSION_CONFIG_KEY="POSTFIX_VERSION"

RELEASE_PACKAGE_NAME="Postfix"
RELEASE_TAG_PACKAGE_NAME="postfix"

TEST_TYPE="background"
TEST_CONTAINER_TYPE="postfix"
TEST_CONTAINER_START_WAIT_SECONDS="10"

short_postfix_version() {
    local full_ver="${1:?}"
    echo "${full_ver:?}" | sed -E 's@^([0-9]+\.[0-9]+\.[0-9]+)-.+$@\1@'
}

current_upstream_version() {
    get_config_arg ${UPSTREAM_VERSION_CONFIG_KEY:?}
}

latest_upstream_version() {
    docker run --rm \
        "$(base_image_name)" \
        sh -c \
        "$(package_version_cmd ${PACKAGES_FILE_PACKAGE_NAME:?})"
}

update_latest_upstream_version() {
    local cur_ver="${1:?}"
    local latest_ver="${2:?}"
    local cur_ver_short="$(short_postfix_version ${cur_ver:?})"
    local latest_ver_short="$(short_postfix_version ${latest_ver:?})"

    echo "Updating ${UPSTREAM_PACKAGE_NAME:?} ${UPSTREAM_VERSION_CONFIG_KEY:?} '${cur_ver:?}' -> '${latest_ver:?}'"
    set_config_arg "${UPSTREAM_VERSION_CONFIG_KEY:?}" "${latest_ver:?}"
    git add ${ARGS_FILE:?}

    if [[ "${cur_ver_short:?}" != "${latest_ver_short:?}" ]]; then
        echo "Updating ${UPSTREAM_PACKAGE_NAME:?} version '${cur_ver_short:?}' -> '${latest_ver_short:?}' in patch files"
        find ${repo_dir:?}/patches -type f -iname '*.diff' -print0 | xargs -0 -r -n 1 sed -i -E "s@/postfix-${cur_ver_short:?}/@/postfix-${latest_ver_short:?}/@g"
        git add ${repo_dir:?}/patches/*.diff
    fi
}

package_current_release_version() {
    current_upstream_version
}

test_start_container() {
    local container_name="${1:?}"
    docker run \
        --name ${container_name:?} \
        --detach \
        --rm \
        ${IMAGE:?}
}

test_image_after_container_startup() {
    local container_name="${1:?}"
    test_tcp_endpoint \
        "${container_name:?}" \
        "$(container_ip "${container_name}")" \
        25 \
        5 \
        '^220 .+ ESMTP Postfix \(Debian\/GNU\)'
}
