---
name: Build

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - '**.md'
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - master
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '00 03 * * *'

permissions:
  contents: read

env:
  PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7
  DOCKERHUB_TEST_TAG: ci-test
  DOCKERHUB_PUBLISH_TAG: ${{ github.ref_name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 120

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Workflow Env vars
        run: make github_env_vars >> $GITHUB_ENV

      - name: Set Up Docker Build Args
        id: docker_build_args
        run: make github_dump_docker_build_args

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.DOCKERHUB_REPO_NAME }}:${{ env.DOCKERHUB_TEST_TAG }}
          build-args: ${{ steps.docker_build_args.outputs.build_args }}

      - name: Test
        run: |
          IMAGE_TAG=${{ env.DOCKERHUB_TEST_TAG }} make test

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{env.PLATFORMS}}
          push: true
          tags: ${{ env.DOCKERHUB_REPO_NAME }}:${{ env.DOCKERHUB_PUBLISH_TAG }}
          build-args: ${{ steps.docker_build_args.outputs.build_args }}
